config/routes.rb
Mychoresweb::Application.routes.draw do

  post "rewards/create"

  post "rewards/update"

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  resources :notifications
  resources :pages
  match '/message/read/:id/:user_id' => "pages#read"

  resources :chores
  match "chores/create" => "chores#create",:via=> [:get,:post]

  resources :points
  match "/points/create" => "points#create", :via => [:get,:post]
  match "/points/show" => "points#show", :via => [:get,:post]
  match "/points/update" => "points#update", :via => [:get,:post]
  match "/points/delete" => "points#delete", :via => [:get,:post]

  resources :kids do
    member do
      get :thumbnail
    end
    resources :points
  end
  match "/kids/create" => "kids#create",:via => [:get, :post]
  match "/kids/update" => "kids#update",:via => [:get, :post]
  match "/kids/delete" => "kids#destroy",:via => :post
  match "/kids/updateChoresConnection" => "kids#update_chore_connection",:via => :post
  match "/kids/deleteChoresConnection" => "kids#delete_chore_connection",:via => :post

  get "root/index"
  match '/' => "pages#index"

  get "root/index"
  match '/login' => "root#login"

  get 'users/create'

  match "/users/create" => "users#create",:via => [:get, :post]
  match "getMessages/:id" => "users#get_messages"
  match "getMessages/:id/:user_id" => "users#get_messages"
  match "deleteMessage/:id" => "users#message_deleted"
  match "readMessage/:id" => "users#message_read"
  get "users/edit"
  get "users/delete"
  get "users/show"
  match "users/check"  => "users#check", :via => [:get,:post]
  match "users/check_updates" => "users#check_updates", :via => [:get,:post]
  match "users/check_updates_since" => "users#check_updates_since", :via => [:get,:post]
  match "/forgotPasscode/:id" => "users#forgot_passcode", :via => [:get,:post]

end

app/models/kid.rb
class Kid < ActiveRecord::Base
  attr_accessible :age, :chore_amount, :name, :picture, :reward_percent, :sex,:local_id,:active
  belongs_to :user
  has_many :points, :dependent => :destroy
  has_many :chore_kids, :dependent => :destroy
  has_many :rewards

  def points
    Point.where(:kid_id => self.id)
  end

  def find_chore_connections
    ch_connections = Array.new
    ch_connection = ChoreKid.find_all_by_kid_id(id)
    ch_connection.each do |c|
        toPush = Hash.new
        toPush['kid_id'] = Kid.find(c.kid_id).local_id
        toPush['chore'] = c.chore_id
        toPush['begin_date'] = c.begin
        toPush['end_date'] = c.end
        toPush['active']=c.active
        ch_connections.push(toPush)
    end
    return ch_connections
  end

  def kid_find_chore_connections_since(date)
    ch_connections = Array.new
    ch_connection = ChoreKid.find_all_by_kid_id(id,:conditions=>['updated_at > ?',date])
    puts date
    puts id
    ch_connection.each do |c|

      toPush = Hash.new
      toPush['kid_id'] = Kid.find(c.kid_id).local_id
      toPush['chore'] = c.chore_id
      toPush['begin_date'] = c.begin
      toPush['end_date'] = c.end
      toPush['active']=c.active

      ch_connections.push(toPush)
    end
    return ch_connections
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  skip_before_filter  :verify_authenticity_token

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kids }
    end
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
    @kid = Kid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/new
  # GET /kids/new.json
  def new
    @kid = Kid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/1/edit
  def edit
    @kid = Kid.find(params[:id])
  end

  # POST /kids
  # POST /kids.json
  def create
    @user = User.find(params[:kid].delete(:user_id))
    @kid = Kid.create(params[:kid])
    @kid.active = true
    @kid.user = @user


    if @kid.save
      render json: @kid
    else
      render json: @kid.errors, status: :unprocessable_entity
    end
  end

  # PUT /kids/1
  # PUT /kids/1.json
  def update
    if params[:kid][:id]
      @kid = Kid.find(params[:kid][:id])
    else
      @kid = Kid.find_by_user_id_and_local_id(params[:kid][:user_id],params[:kid][:local_id])
    end
    params[:kid].delete(:user_id)
    params[:kid].delete(:id)
    if @kid.update_attributes(params[:kid])
      render json: @kid
    else
      render json: @kid.errors, status: :unprocessable_entity
    end
  end


  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid = Kid.find_by_user_id_and_local_id(params[:user_id],params[:id])
    if @kid
      @kid.active = false
      @kid.save
    end


    render json: "deleted"
  end

  def thumbnail
    @kid = Kid.find(params[:id])
    send_data @kid.picture, :type => 'image/png',:disposition => "inline"
  end

  def update_chore_connection
    params[:data].each do |c|
      @user = User.find(c['user_id'])
      @kid = @user.kids.where(:local_id => c['local_kid']).first
      exists = ChoreKid.where(:kid_id => @kid.id,:chore_id => c['local_chore_id'], :begin => c['begin_date'], :end => c['end_date'])
      if exists.empty?
        ChoreKid.create(:kid_id => @kid.id,:chore_id => c['local_chore_id'], :begin => c['begin_date'], :end => c['end_date'])
      end
    end
    render :json => {'status'=> :updated}
  end

  def delete_chore_connection
    c = params[:data]
    user = User.find(c[:user_id])
    kid = user.kids.where(:local_id => c[:local_kid_id]).first
    exists = ChoreKid.where(:kid_id => kid.id,:chore_id => c['chore_id'], :begin => c['begin'], :end => c['end'])
    kid.points.where(:chore_id => c[:chore_id] , :date =>c[:begin]..c[:end] ).delete_all

    if !exists.empty?
      exists.each do |e|
        e.active = 0
        e.save
      end
    end
    render :json => {'status'=> :updated}

  end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_area :sex %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :chore_amount %><br />
    <%= f.number_field :chore_amount %>
  </div>
  <div class="field">
    <%= f.label :reward_percent %><br />
    <%= f.number_field :reward_percent %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<h1>Listing kids</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sex</th>
    <th>Age</th>
    <th>Parent</th>
    <th>Chore amount</th>
    <th>Reward percent</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kids.each do |kid| %>
  <tr>
    <td><%= kid.name %></td>
    <td><%= kid.sex %></td>
    <td><%= kid.age %></td>
    <td><%= kid.user_id %></td>
    <td><%= kid.chore_amount %></td>
    <td><%= kid.reward_percent %></td>
    <td>  <%= ('<img src="data:image/jpg;base64,%s">' % kid.picture).html_safe %>
    <td><%= link_to 'Show', kid %></td>
    <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
    <td><%= link_to 'Destroy', kid, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @kid.name %>
</p>

<p>
  <b>Sex:</b>
  <%= @kid.sex %>
</p>

<p>
  <b>Age:</b>
  <%= @kid.age %>
</p>

<p>
  <b>Parent:</b>
  <%= @kid.user_id %>
</p>

<p>
  <b>Chore amount:</b>
  <%= @kid.chore_amount %>
</p>

<p>
  <b>Reward percent:</b>
  <%= @kid.reward_percent %>
</p>

<p>
  <b>Picture:</b>
  <%= ('<img src="data:image/jpg;base64,%s">' % @kid.picture).html_safe %>
</p>


<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>