config/routes.rb
Mychoresweb::Application.routes.draw do

  post "rewards/create"

  post "rewards/update"

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  resources :notifications
  resources :pages
  match '/message/read/:id/:user_id' => "pages#read"

  resources :chores
  match "chores/create" => "chores#create",:via=> [:get,:post]

  resources :points
  match "/points/create" => "points#create", :via => [:get,:post]
  match "/points/show" => "points#show", :via => [:get,:post]
  match "/points/update" => "points#update", :via => [:get,:post]
  match "/points/delete" => "points#delete", :via => [:get,:post]

  resources :kids do
    member do
      get :thumbnail
    end
    resources :points
  end
  match "/kids/create" => "kids#create",:via => [:get, :post]
  match "/kids/update" => "kids#update",:via => [:get, :post]
  match "/kids/delete" => "kids#destroy",:via => :post
  match "/kids/updateChoresConnection" => "kids#update_chore_connection",:via => :post
  match "/kids/deleteChoresConnection" => "kids#delete_chore_connection",:via => :post

  get "root/index"
  match '/' => "pages#index"

  get "root/index"
  match '/login' => "root#login"

  get 'users/create'

  match "/users/create" => "users#create",:via => [:get, :post]
  match "getMessages/:id" => "users#get_messages"
  match "getMessages/:id/:user_id" => "users#get_messages"
  match "deleteMessage/:id" => "users#message_deleted"
  match "readMessage/:id" => "users#message_read"
  get "users/edit"
  get "users/delete"
  get "users/show"
  match "users/check"  => "users#check", :via => [:get,:post]
  match "users/check_updates" => "users#check_updates", :via => [:get,:post]
  match "users/check_updates_since" => "users#check_updates_since", :via => [:get,:post]
  match "/forgotPasscode/:id" => "users#forgot_passcode", :via => [:get,:post]

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :page_id,:title,:recipients,:sound,:badge

  after_create :send_notification


  def send_notification

    pusher = Grocer.pusher(
        certificate: File.join(Rails.root,"db/certificates/mychorescert.pem"),
        gateway:     "gateway.sandbox.push.apple.com", # optional; See note below.
        port:        2195,
        retries:     5                         # optional
    )

    deviceIds = Array.new
    searchParams = JSON.parse(recipients)

    if searchParams['all'] == "1"
      deviceIds = Device.where(:active => true)
    elsif searchParams['devices'] != ''
      #have to split them
      deviceIds = searchParams['devices'].split(",").each {|t| t.strip!}
      deviceIds = Device.find_all_by_identifier(deviceIds,:conditions => {active:true})

    else
      #start Searching....
      @users = User.scoped
      @users = @users.where(:id => Kid.where(:age => searchParams['ages'].to_i).select(:user_id).group(:user_id).map(&:user_id)) unless searchParams['ages'].blank?
      @users = @users.where(:id => Chore.where(:local_chore_id => searchParams['chore'].to_i).select(:user_id).group(:user_id).map(&:user_id)) unless searchParams['chore'].blank?
      @users = @users.where(:country => searchParams['country']) unless searchParams['country'].blank?
      @users = @users.where(:language => searchParams['language']) unless searchParams['language'].blank?

      if !@users.empty?
        @users.each do |u|
          deviceIds << u.devices.where(:active => true) .first

        end
      end
    end



    deviceIds.flatten.each do |device|
      PageUser.where(:user_id => device.user_id, :device_token => device.identifier,:page_id => page_id).first_or_create unless page_id.blank?

      if !device.identifier.include?('nopush')
        notification = Grocer::Notification.new(
            device_token: device.identifier,
            alert: { "body" =>  title}
        )

        notification.custom = {:acme2 => ["new message", "1"],:message_title => title} unless page_id.blank?

        notification.sound = 'default'
        notification.badge = badge.to_i unless badge.blank?


        pusher.push(notification)
      end

    end
  end



end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    params[:notification][:recipients] = params[:recipient].to_json
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %><br />
  </div>
  <div class="field">
    <%= f.label :sound %>
    <%= f.text_field :sound %><br />
  </div>
  <div class="field">
    <%= f.label :badge %>
    <%= f.number_field :badge %><br />
  </div>
  <div class="field">
    <%= f.label :page_id %>
    <%= f.select(:page_id,Page.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'}) %><br />
    <div class="linkWrap">
      <%= link_to('Preview','/message/read/' ) %>
    </div>
  </div>
  <div class="recipientWrapper">
    <p>Send To:</p>
    <%= f.check_box :id, :name => 'recipient[all]', :value => 'all' %> Send to all<br />
    <fieldset>
      Filter By
      <p>Age:</p>
      <%= f.text_field :id, :name => 'recipient[ages]', :placeholder => '2,5,6' %><br />
      <p>Country:</p>
      <%= f.text_field :id, :name => 'recipient[country]', :placeholder => 'US,CR,CA' %><br />
      <p>Language:</p>
      <%= f.text_field :id, :name => 'recipient[language]', :placeholder => 'ES'%><br />
      <p>Chore ID:</p>
      <%= f.text_field :id, :name => 'recipient[chore]', :placeholder => '1,3,4'%><br />
      <p>Specific Device Ids:</p>
      <%= f.text_field :id, :name => 'recipient[devices]', :placeholder => '123456789,9876543'%><br />
    </fieldset>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  $('#notification_page_id').live('change',function(){
      $('.linkWrap a').attr('href','/message/read/'+ $(this).val()+'/0');
  })
</script>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Recipients</th>
    <th>Sound</th>
    <th>Badge</th>
    <th>Created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.id %></td>
    <td><%= notification.title %></td>
    <td><%= notification.recipients %></td>
    <td><%= notification.sound %></td>
    <td><%= notification.badge %></td>
    <td><%= notification.created_at %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>