config/routes.rb
Mychoresweb::Application.routes.draw do

  post "rewards/create"

  post "rewards/update"

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  resources :notifications
  resources :pages
  match '/message/read/:id/:user_id' => "pages#read"

  resources :chores
  match "chores/create" => "chores#create",:via=> [:get,:post]

  resources :points
  match "/points/create" => "points#create", :via => [:get,:post]
  match "/points/show" => "points#show", :via => [:get,:post]
  match "/points/update" => "points#update", :via => [:get,:post]
  match "/points/delete" => "points#delete", :via => [:get,:post]

  resources :kids do
    member do
      get :thumbnail
    end
    resources :points
  end
  match "/kids/create" => "kids#create",:via => [:get, :post]
  match "/kids/update" => "kids#update",:via => [:get, :post]
  match "/kids/delete" => "kids#destroy",:via => :post
  match "/kids/updateChoresConnection" => "kids#update_chore_connection",:via => :post
  match "/kids/deleteChoresConnection" => "kids#delete_chore_connection",:via => :post

  get "root/index"
  match '/' => "pages#index"

  get "root/index"
  match '/login' => "root#login"

  get 'users/create'

  match "/users/create" => "users#create",:via => [:get, :post]
  match "getMessages/:id" => "users#get_messages"
  match "getMessages/:id/:user_id" => "users#get_messages"
  match "deleteMessage/:id" => "users#message_deleted"
  match "readMessage/:id" => "users#message_read"
  get "users/edit"
  get "users/delete"
  get "users/show"
  match "users/check"  => "users#check", :via => [:get,:post]
  match "users/check_updates" => "users#check_updates", :via => [:get,:post]
  match "users/check_updates_since" => "users#check_updates_since", :via => [:get,:post]
  match "/forgotPasscode/:id" => "users#forgot_passcode", :via => [:get,:post]

end

app/views/pages/index.html.haml
%h1
  Messages
%ul
  - @pages.each do |page|
    %li= link_to page.name,page

= link_to 'New Page', new_page_path

app/views/pages/read.html.haml
.content
  =@page.content

app/views/pages/show.html.haml
%p= link_to "Edit Page", "/editor" + request.path, id: "edit_link", data: {save_url: page_path(@page)}
%p= link_to "Back to main pages", pages_path

#header
  %h1#page_name.mercury-region{"data-mercury"=>"simple"}
    = raw @page.name

.content
  #page_content.mercury-region{"data-mercury"=>"full"}
    = raw @page.content